// Derivative paths for the personal portrait, generated by `npm run photo`
// (scripts/photo.mjs) into /public/photo/. One place to change a filename.
//
// Everything is gated on SITE.hasPhoto — while that is false the site falls
// back to what it showed before (the "PL" monogram), so a missing file can
// never render as a broken image.

import { SITE } from '../config';

export const hasPhoto = SITE.hasPhoto;

export const PHOTO = {
  /** About page portrait, 4:5. */
  portrait: '/photo/patrick-720.webp',
  /** Small round avatar for the article author box. */
  avatar: '/photo/patrick-128.webp',
  avatar2x: '/photo/patrick-256.webp',
  /** Square JPEG for JSON-LD / rich results (crawlers want a stable raster). */
  schema: '/photo/patrick-square.jpg',
  /** Favicons. */
  icon32: '/photo/icon-32.png',
  icon180: '/photo/apple-touch-icon.png',
  icon512: '/photo/icon-512.png',
} as const;
